import OtpConfirmForm from "@/src/components/OtpConfirmForm";
import { type Metadata } from "next";

export const metadata: Metadata = {
    title: 'Confirm Email',
    description: 'Generated by create next app',
}

export default function Login({ searchParams }: {
    searchParams?: {
        back: string
    }
}){
    return (
    <main className="flex h-full w-full flex-col justify-center items-center">
        <h1 className="text-center">Please login here</h1>
        <div className="p-5 m-0">
            <OtpConfirmForm />
        </div>
    </main>);
}
